joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
joint1_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: joint1
  pid: {p: 140.0, i: 0.1, d: 10.0}
